/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "hmc5983.h" 
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_LISTVIEW_0 (GUI_ID_USER + 0x01)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END
#define whide 80
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 20, 800, 440, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
  WM_HWIN hItem;
 void _cbDialog(WM_MESSAGE * pMsg) {

  int     NCode;
  int     Id;
    char buf[20]={0};
    uint8_t i;
  // USER START (Optionally insert additional variables)
  // USER END
 i++;
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    LISTVIEW_AddColumn(hItem, 60, "MAG", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 60, "X", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 60, "Y", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddRow(hItem, NULL);
      LISTVIEW_AddRow(hItem, NULL);
      LISTVIEW_AddRow(hItem, NULL);
      LISTVIEW_AddRow(hItem, NULL);
      LISTVIEW_AddRow(hItem, NULL);
      LISTVIEW_AddRow(hItem, NULL);
  
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_AddColumn(hItem, 60, "Z", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, "K", GUI_TA_HCENTER | GUI_TA_VCENTER);
//    LISTVIEW_AddColumn(hItem, 40, "Ky", GUI_TA_HCENTER | GUI_TA_VCENTER);
//    LISTVIEW_AddColumn(hItem, 40, "Kz", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, "A0", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 60, "A1x", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 60, "A1y", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 60, "A1z", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetItemText(hItem, 0, 0, "MAG1");
    LISTVIEW_SetItemText(hItem, 0, 1, "MAG2");
    LISTVIEW_SetItemText(hItem, 0, 2, "MAG3");
    LISTVIEW_SetItemText(hItem, 0, 3, "MAG4");
    LISTVIEW_SetItemText(hItem, 0, 4, "MAG5");
    LISTVIEW_SetItemText(hItem, 0, 5, "MAG6");
    LISTVIEW_SetItemText(hItem, 0, 6, "MAG7");
    LISTVIEW_SetItemText(hItem, 2, 0, "Item\n123\n68");
    LISTVIEW_SetFont(hItem, GUI_FONT_16_1);
    LISTVIEW_AddColumn(hItem, 80, "difference", GUI_TA_HCENTER | GUI_TA_VCENTER);
    //LISTVIEW_AddColumn(hItem, 80, "difference", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetRowHeight(hItem, 60);
    LISTVIEW_SetHeaderHeight(hItem, 25);
    for(i=1;i<8;i++)
    {
    snprintf(buf,20,"%.2f\n%.2f\n%.2f\n",hmc5983.kx[i],hmc5983.ky[i],hmc5983.kz[i]);
    LISTVIEW_SetItemText(hItem, 4, i-1, buf);
    snprintf(buf,20,"%d\n%d\n%d\n",hmc5983.a0x[i],hmc5983.a0y[i],hmc5983.a0z[i]);
    LISTVIEW_SetItemText(hItem, 5, i-1, buf);
    }
//          for(i=1;i<8;i++)
//    {
//    snprintf(buf,20,"%d\n%d\n%d\n",hmc5983.x[i],hmc5983.y[i],hmc5983.z[i]);
//    LISTVIEW_SetItemText(hItem, 1, i-1, buf);
////        LISTVIEW_DeleteRow(hItem,i-1);
//    }
 
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
 case WM_NOTIFY_PARENT:
    Id    = ID_LISTVIEW_0;// WM_GetId(pMsg->hWinSrc);
    NCode = WM_NOTIFICATION_SEL_CHANGED;
//           GUI_EndDialog(hItem, 0);
        
//    Id    = WM_GetId(pMsg->hWinSrc);
//    NCode = pMsg->Data.v;
        
        
    switch(Id) {
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
//           for(i=1;i<8;i++)
//    {
//    snprintf(buf,20,"%d\n%d\n%d\n",hmc5983.x[i],hmc5983.y[i],hmc5983.z[i]);
//    LISTVIEW_SetItemText(hItem, 1, i-1, buf);
//    }
      
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
//     for(i=1;i<8;i++)
//    {
//    snprintf(buf,20,"%d\n%d\n%d\n",hmc5983.x[i],hmc5983.y[i],hmc5983.z[i]);
//    LISTVIEW_SetItemText(hItem, 1, i-1, buf);
////    snprintf(buf,20,"%d\n%d\n%d\n",hmc5983.a0x[i],hmc5983.a0y[i],hmc5983.a0z[i]);
////    LISTVIEW_SetItemText(hItem, 5, i-1, buf);
//    }
 
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
 // WM_DeleteWindow(hWin);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
